- id: doi:10.1038/ng.2272
  image: https://media.springernature.com/full/springer-static/image/art%3A10.1038%2Fng.2272/MediaObjects/41588_2012_Article_BFng2272_Fig1_HTML.jpg?as=webp
  tags:
    - GWAS
    - Vitiligo
    
- id: doi:10.1371/journal.pgen.1006174
  image: https://journals.plos.org/plosgenetics/article/figure/image?size=large&id=10.1371/journal.pgen.1006174.g002
  tags:
    - GWAS
    - Facial Shape
  extra-links:
    - type: external
      text: FaceBase Consortium
      link: https://facebase.org/

- id: doi:10.1371/journal.pgen.1006149
  image: https://journals.plos.org/plosgenetics/article/figure/image?size=large&id=10.1371/journal.pgen.1006149.g001
  tags:
    - GWAS
    - Facial Shape
  extra-links:
    - type: external
      text: FaceBase Consortium
      link: https://facebase.org/  

- id: doi:10.1534/genetics.116.193185
  image: https://oup.silverchair-cdn.com/oup/backfile/Content_public/Journal/genetics/205/2/10.1534_genetics.116.193185/8/967fig3.jpeg?Expires=1669683544&Signature=RVg8qJLVh6Y7gojv9PkbawA0ZiOXhYwDKdWoy1hS6c7-FUDfWgifEDAgPj8AUQGEIv1ngNo3qhiMlyWuhLDbHEqJvzp-p8xWfOB7MVnbErVhxkwXu56E1yjVhMIvobPtlK1iMy3LgpWGu02oYsWgfD2KyB3uxXEaxoPfwx~og3PUvQT76ZUEix~78NiPC11UPQhHFExNhIMTExc-MiH3nlTcvcTMbLH2vJqLxZ2w2t~5Q5nCNx01-Rq8p~gS6EPawlPp6C1Z2NK8lofhPbcIQNtoWRdwSNkgUznP93~pLAonmkBXl9Vr0s~8DVvLhtgqsceNxJ~5BPLGUl~uMN1g7g__&Key-Pair-Id=APKAIE5G5CRDK6RD3PGA
  tags:
    - Heritability
    - Facial Shape
    - Body Size
  extra-links:
    - type: external
      text: FaceBase Consortium
      link: https://facebase.org/ 
    
- id: doi:doi:10.1111/joa.12576
  image: https://onlinelibrary.wiley.com/cms/asset/a1369356-f816-42e9-b5d9-65a64daaaf1d/joa12576-fig-0002-m.jpg
  tags:
    - Software
    - Phenotyping
    - Facial Shape
  extra-links:
    - type: external
      text: FaceBase Consortium
      link: https://facebase.org/
    - type: source
      text: Software
      link: https://www.facebase.org/facial_landmarking/
      
- id: doi:10.1111/joa.12748
  image: https://onlinelibrary.wiley.com/cms/asset/b33f654c-8d32-42e0-9fae-8e93b8fabb8e/joa12748-fig-0007-m.jpg
  tags:
    - Genetic and Environmental Variance
    - Facial Shape
    - Body Size
    - Growth Faltering
  extra-links:
    - type: website
      text: FaceBase Consortium
      link: https://facebase.org/  

      
- id: doi:10.1002/ajpa.23356
  image: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5777898/bin/nihms916793f6.jpg
  tags:
    - Facial Shape
    - Body Size
  extra-links:
    - type: website
      text: FaceBase Consortium
      link: https://facebase.org/  

- id: doi:10.1371/journal.pmed.1002654
  image: https://journals.plos.org/plosmedicine/article/figure/image?size=large&id=10.1371/journal.pmed.1002654.g001
  tags:
    - Method
    - Genetic Subtyping
    - Polygenic Scores
    - Type 2 Diabetes
  extra-links:
    - type: source
      text: Code
      link: https://github.com/gwas-partitioning/bnmf-clustering

- id: doi:10.1681/asn.2019030218
  image: https://jasn.asnjournals.org/content/jnephrol/30/10/2000/F1.large.jpg?width=800&height=600&carousel=1
  tags:
    - GWAS
    - Diabetic Kidney Disease
  extra-links:
    - type: data
      text: Summary Statistics
      link: http://www.type2diabetesgenetics.org/informational/data
      
- id: doi:10.1038/s41581-020-0278-5
  image: https://media.springernature.com/full/springer-static/image/art%3A10.1038%2Fs41581-020-0278-5/MediaObjects/41581_2020_278_Fig1_HTML.png?as=webp
  tags:
    - Review
    - Diabetic Kidney Disease

- id: doi:10.1038/s41467-020-15193-0
  image: https://media.springernature.com/full/springer-static/image/art%3A10.1038%2Fs41467-020-15193-0/MediaObjects/41467_2020_15193_Fig1_HTML.png?as=webp
  tags:
    - GWAS
    - Dietary Intake
  extra-links:
    - type: data
      text: Summary Statistics
      link: https://www.kp4cd.org/dataset_downloads/t2d

- id: doi:10.1038/s41366-020-0603-x
  image: https://media.springernature.com/full/springer-static/image/art%3A10.1038%2Fs41366-020-0603-x/MediaObjects/41366_2020_603_Fig3_HTML.png?as=webp
  tags:
    - Software
    - Metabolomics
    - Obesity
  extra-links:
    - type: source
      text: Software
      link: https://github.com/yuhanhsu/PAIRUP-MS

- id: doi:10.1038/s41591-020-0893-5

- id: doi:10.1038/s41467-021-23556-4

- id: doi:10.1038/s41467-021-21952-4

- id: doi:10.1371/journal.pmed.1003553

- id: doi:10.1186/s13148-021-01081-x

- id: doi:10.1186/s13075-021-02444-8

- id: doi::10.1093/hmg/ddab109

- id: doi:10.1186/s12920-021-00978-z

- id: doi:10.3389/fgene.2022.997266

- id: doi:10.2337/dc21-1395

- id: doi:10.1016/j.xhgg.2021.100082

- id: doi:10.2337/db21-0545

- id: doi:10.1007/s00125-022-05735-0

- id: doi:10.1038/s41586-022-05067-4

- id: doi:10.1038/s41467-022-31625-5
