- id: doi:10.1038/ng.2272
  image: https://media.springernature.com/full/springer-static/image/art%3A10.1038%2Fng.2272/MediaObjects/41588_2012_Article_BFng2272_Fig1_HTML.jpg?as=webp
  tags:
    - GWAS
    - Vitiligo
    
- id: doi:10.1371/journal.pgen.1006174
  image: https://journals.plos.org/plosgenetics/article/figure/image?size=large&id=10.1371/journal.pgen.1006174.g002
  tags:
    - GWAS
    - Facial Shape
  extra-links:
    - type: external
      text: FaceBase Consortium
      link: https://facebase.org/

- id: doi:10.1371/journal.pgen.1006149
  image: https://journals.plos.org/plosgenetics/article/figure/image?size=large&id=10.1371/journal.pgen.1006149.g001
  tags:
    - GWAS
    - Facial Shape
  extra-links:
    - type: external
      text: FaceBase Consortium
      link: https://facebase.org/  

- id: doi:10.1534/genetics.116.193185
  image: https://oup.silverchair-cdn.com/oup/backfile/Content_public/Journal/genetics/205/2/10.1534_genetics.116.193185/8/967fig3.jpeg?Expires=1669683544&Signature=RVg8qJLVh6Y7gojv9PkbawA0ZiOXhYwDKdWoy1hS6c7-FUDfWgifEDAgPj8AUQGEIv1ngNo3qhiMlyWuhLDbHEqJvzp-p8xWfOB7MVnbErVhxkwXu56E1yjVhMIvobPtlK1iMy3LgpWGu02oYsWgfD2KyB3uxXEaxoPfwx~og3PUvQT76ZUEix~78NiPC11UPQhHFExNhIMTExc-MiH3nlTcvcTMbLH2vJqLxZ2w2t~5Q5nCNx01-Rq8p~gS6EPawlPp6C1Z2NK8lofhPbcIQNtoWRdwSNkgUznP93~pLAonmkBXl9Vr0s~8DVvLhtgqsceNxJ~5BPLGUl~uMN1g7g__&Key-Pair-Id=APKAIE5G5CRDK6RD3PGA
  tags:
    - Heritability
    - Facial Shape
    - Body Size
  extra-links:
    - type: external
      text: FaceBase Consortium
      link: https://facebase.org/ 

- id: doi:10.1002/9780470015902.a0027240
  image: https://onlinelibrary.wiley.com/cms/asset/6a6dbae1-b69c-45b5-8bd3-cc464ee00bd3/047001590x.cover.jpg
  tags:
    - Review
    - Facial Shape

- id: doi:doi:10.1111/joa.12576
  image: https://onlinelibrary.wiley.com/cms/asset/a1369356-f816-42e9-b5d9-65a64daaaf1d/joa12576-fig-0002-m.jpg
  tags:
    - Software
    - Phenotyping
    - Facial Shape
  extra-links:
    - type: external
      text: FaceBase Consortium
      link: https://facebase.org/
    - type: source
      text: Software
      link: https://www.facebase.org/facial_landmarking/
      
- id: doi:10.1111/joa.12748
  image: https://onlinelibrary.wiley.com/cms/asset/b33f654c-8d32-42e0-9fae-8e93b8fabb8e/joa12748-fig-0007-m.jpg
  tags:
    - Genetic and Environmental Variance
    - Facial Shape
    - Body Size
    - Growth Faltering
  extra-links:
    - type: website
      text: FaceBase Consortium
      link: https://facebase.org/  

- id: doi:10.1002/ajpa.23356
  image: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5777898/bin/nihms916793f6.jpg
  tags:
    - Facial Shape
    - Body Size
  extra-links:
    - type: website
      text: FaceBase Consortium
      link: https://facebase.org/  

- id: doi:10.1371/journal.pmed.1002654
  image: https://journals.plos.org/plosmedicine/article/figure/image?size=large&id=10.1371/journal.pmed.1002654.g001
  tags:
    - Method
    - Genetic Subtypes
    - Polygenic Scores
    - Type 2 Diabetes
  extra-links:
    - type: source
      text: Code
      link: https://github.com/gwas-partitioning/bnmf-clustering

- id: doi:10.1681/asn.2019030218
  image: https://jasn.asnjournals.org/content/jnephrol/30/10/2000/F1.large.jpg?width=800&height=600&carousel=1
  tags:
    - GWAS
    - Diabetic Kidney Disease
  extra-links:
    - type: data
      text: Summary Statistics
      link: http://www.type2diabetesgenetics.org/informational/data
      
- id: doi:10.1038/s41581-020-0278-5
  image: https://media.springernature.com/full/springer-static/image/art%3A10.1038%2Fs41581-020-0278-5/MediaObjects/41581_2020_278_Fig1_HTML.png?as=webp
  tags:
    - Review
    - Diabetic Kidney Disease

- id: doi:10.1038/s41467-020-15193-0
  image: https://media.springernature.com/full/springer-static/image/art%3A10.1038%2Fs41467-020-15193-0/MediaObjects/41467_2020_15193_Fig1_HTML.png?as=webp
  tags:
    - GWAS
    - Dietary Intake
  extra-links:
    - type: data
      text: Summary Statistics
      link: https://www.kp4cd.org/dataset_downloads/t2d

- id: doi:10.1038/s41366-020-0603-x
  image: https://media.springernature.com/full/springer-static/image/art%3A10.1038%2Fs41366-020-0603-x/MediaObjects/41366_2020_603_Fig3_HTML.png?as=webp
  tags:
    - Software
    - Metabolomics
    - Obesity
  extra-links:
    - type: source
      text: Software
      link: https://github.com/yuhanhsu/PAIRUP-MS

- id: doi:10.1038/s41591-020-0893-5
  image: https://media.springernature.com/full/springer-static/image/art%3A10.1038%2Fs41591-020-0893-5/MediaObjects/41591_2020_893_Fig2_HTML.png?as=webp
  tags:
    - Variant-to-Function (V2F)
    - Parkinson’s Disease

- id: doi:10.1038/s41467-021-23556-4
  image: https://media.springernature.com/lw685/springer-static/image/art%3A10.1038%2Fs41467-021-23556-4/MediaObjects/41467_2021_23556_Fig3_HTML.png?as=webp
  tags:
    - Penetrance
    - Polygenic Scores
    - Monogenic Diabetes
    
- id: doi:10.1038/s41467-021-21952-4
  image: https://media.springernature.com/lw685/springer-static/image/art%3A10.1038%2Fs41467-021-21952-4/MediaObjects/41467_2021_21952_Fig3_HTML.png?as=webp
  tags:
    - Software
    - GWAS
    - Recessive
  extra-links:
    - type: source
      text: Software
      link: https://gitlab.bsc.es/computational-genomics/guidance
    
- id: doi:10.1371/journal.pmed.1003553
  image: https://journals.plos.org/resource/img/logo-plos.png
  tags:
    - Mendelian Randomization
    - COVID-19
    - Obesity
    
- id: doi:10.1186/s13148-021-01081-x
  image: https://media.springernature.com/lw685/springer-static/image/art%3A10.1186%2Fs13148-021-01081-x/MediaObjects/13148_2021_1081_Fig1_HTML.png?as=webp
  tags:
    - DNA Methylation
    - Diabetic Kidney Disease

- id: doi:10.1186/s13075-021-02444-8
  image: https://media.springernature.com/lw685/springer-static/image/art%3A10.1186%2Fs13075-021-02444-8/MediaObjects/13075_2021_2444_Fig2_HTML.png?as=webp
  tags:
    - Mendelian Randomization
    - Hyperuricemia
    - Dietary Intake

- id: doi:10.1093/hmg/ddab109
  image: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC8411984/bin/ddab109f3.jpg
  tags:
    - Gene-Environment Interactions
    - Type 2 Diabetes
    - Dietary Intake

- id: doi:10.1186/s12920-021-00978-z
  image: https://media.springernature.com/lw685/springer-static/image/art%3A10.1186%2Fs12920-021-00978-z/MediaObjects/12920_2021_978_Fig3_HTML.png?as=webp
  tags:
    - Structural Variation
    - Penetrance
    
- id: doi:10.3389/fgene.2022.997266
  image: https://d2csxpduxe849s.cloudfront.net/media/E32629C6-9347-4F84-81FEAEF7BFA342B3/736B937B-CCA4-4440-B731C5C595C623EA/WebsiteWebP_XL-shutterstock_1895343883.webp
  tags:
    - Editorial
    - Nutrigenomics

- id: doi:10.2337/dc21-1395
  image: https://ada.silverchair-cdn.com/ada/content_public/journal/care/45/3/10.2337_dc21-1395/4/m_dc211395f1.png?Expires=1669277275&Signature=cZgj2n1yFSjFQBhh4zZJ6A-LKf9LZDRvskchz6br9CHAjgvjg-so2iwvsHpzJfQPU6Buwa~h1-OcGkv5N80NZmc~wopJioRFJ8QPQXP4o9Wl1J30pG8-OK1DyROFWWLzAy6kqXNL7tiEm2LsCihc7tWVE7FVbSifAkdmRj86R~xOEgStUySKM~BpZslbvc8g9mzIfeBUZ~k-l-MVciAEIAT4zl2TbtuRtX24zeVlXLU0zl05zA6OaH0oO5bzYNLCNUsifhj0UR~MkFvU9n~IOIZb4yrNh7fRCTpMAILuYbpYPxXSxtdrYGZbOWgoh8UPzmjOLhwk1UqabTsfxYiuQA__&Key-Pair-Id=APKAIE5G5CRDK6RD3PGA
  tags:
    - Genetic Subtypes
    - Polygenic Scores
    - Type 2 Diabetes

- id: doi:10.1016/j.xhgg.2021.100082
  image: https://ars.els-cdn.com/content/image/1-s2.0-S2666247721000634-gr3.jpg
  tags:
    - CNV GWAS
    - Structural Variation
    - Facial Shape

- id: doi:10.2337/db21-0545
  image: https://ada.silverchair-cdn.com/ada/content_public/journal/diabetes/71/3/10.2337_db21-0545/4/m_db210545f1.png?Expires=1668890139&Signature=dp-A~emp~u7eHppLpmufBtBijhQUfRPoP~2UfQ5g~m8zCZGElrq6X-v2rLN11ToG9isOgn9UrveoAENt-6AWkrBV~UKc3YD1UyseoOiUBaeUm4A1cpyVLMLJK~ugpJfShLTS~Oe1ss-Gw1dZQfxg2M1inLBrdJ31B1owN2M3rUUF1xcaTmprHjkyViu3SlF7Lssym-7WQkPAW1Jdg7Bqi4kXct5POu21sTOkfmKYzc5aw0bAnbje5OSgNABySiMcA3GkKW25QlCPbtGVNmsSDWRs~Yd9swihISJRmjkNP9Ztuu-NQMjbKrmL9~Z7uWOWlXPId2B~f6fz5kktVI56Uw__&Key-Pair-Id=APKAIE5G5CRDK6RD3PGA
  tags:
    - GWAS
    - Recessive
    - Type 2 Diabetes

- id: doi:10.1007/s00125-022-05735-0
  image: https://media.springernature.com/lw685/springer-static/image/art%3A10.1007%2Fs00125-022-05735-0/MediaObjects/125_2022_5735_Figa_HTML.png?as=webp
  tags:
    - GWAS
    - Multi-omics
    - Diabetic Kidney Disease
    
- id: doi:10.1038/s41586-022-05067-4
  image: https://media.springernature.com/lw685/springer-static/image/art%3A10.1038%2Fs41586-022-05067-4/MediaObjects/41586_2022_5067_Fig5_HTML.png?as=webp
  tags:
    - Functional Characterization
    
- id: doi:10.1038/s41467-022-31625-5
  image: https://media.springernature.com/lw685/springer-static/image/art%3A10.1038%2Fs41467-022-31625-5/MediaObjects/41467_2022_31625_Fig3_HTML.png?as=webp
  tags:
    - Method
    - Gene-Environment Interactions
    - Biomarkers
  extra-links:
    - type: source
      text: Software
      link: https://github.com/kwesterman/vqtl-gxe
    - type: data
      text: Data
      link: https://hugeamp.org/research.html?pageid=UKB-vQTL-GxE
    
- id: doi:10.1038/s41588-022-01200-1
  image: https://media.springernature.com/lw685/springer-static/image/art%3A10.1038%2Fs41588-022-01200-1/MediaObjects/41588_2022_1200_Fig3_HTML.png?as=webp
    tags:
    - Polygenic Scores
    - Type 2 Diabetes
